---
environment_variables:
  NEXTCLOUD_VERSION: "DEV-MFA-1"
git:
  branch: main
triggers:
  cron: "@daily"
clean_workspace: true
builders:
  - docker
docker_name: drive/nextcloud-custom
docker_tags:
  - "${NEXTCLOUD_VERSION}"
  - "latest"
docker_no_cache: true
