---
environment_variables:
  NEXTCLOUD_VERSION: "20.0.12"
git:
  branch: main
triggers:
  cron: "@daily"
clean_workspace: true
builders:
  - docker
docker_name: drive/nextcloud-custom
docker_tags:
  - "${NEXTCLOUD_VERSION}"
docker_no_cache: true
extra_jobs:
  - name: drive-nextcloud-19
    environment_variables:
      NEXTCLOUD_VERSION: "19.0.13.1"
    git:
      branch: nextcloud-19
    triggers:
      cron: "@daily"
    clean_workspace: true
    builders:
      - docker
    docker_name: drive/nextcloud-custom-19
    docker_tags:
      - "${NEXTCLOUD_VERSION}"
    docker_no_cache: true
